title: deepakbapat.com
email: deepakbapat.github@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "deepakbapat.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: deepakabapat
github_username:  deepakbapat

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

